version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double Trouble"
workflows:
  version: 2
  echo1_echo2:
    jobs:
      - echo1
      - echo2
